import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Menu App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title} style={{fontSize: '10rem'}}>
          Bienvenido
        </h1>

        <p className={styles.description}>
          Inicia sesión
        </p>

      </main>
    </div>
  )
}

export default Home
