import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Menu App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="p-4">
                <h1 className="text-title font-thin">Bienvenido</h1>
                <h1 className="text-title font-light">Bienvenido</h1>
                <h1 className="text-title font-normal">Bienvenido</h1>
                <h1 className="text-title font-medium">Bienvenido</h1>
                <h1 className="text-title font-semiBold">Bienvenido</h1>
                <h1 className="text-title font-bold">Bienvenido</h1>

                <p className="text-xl">Inicia sesión</p>
            </main>
        </div>
    );
};

export default Home;
